PUBMED_ESEARCH_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
PUBMED_EFETCH_URL = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
RETMAX = 50
PUBMED_CAP = 500

DISEASE_VOCABULARY = [
    "malaria",
    "HIV",
    "tuberculosis",
    "pneumonia",
    "cholera",
    "typhoid fever",
    "meningitis",
    "hepatitis B",
    "hepatitis C",
    "diarrhoeal disease",
    "yellow fever",
    "dengue fever",
    "ebola",
    "mpox",
    "schistosomiasis",
    "onchocerciasis",
    "lymphatic filariasis",
    "trachoma",
    "trypanosomiasis",
    "leishmaniasis",
    "buruli ulcer",
    "leprosy",
    "guinea worm",
    "soil-transmitted helminths",
    "sickle cell disease",
    "G6PD deficiency",
    "thalassaemia",
    "malnutrition",
    "neonatal sepsis",
    "obstetric fistula",
    "preeclampsia",
    "stunting",
    "lassa fever",
    "marburg virus",
    "rift valley fever",
]
TREATMENT_KEYWORDS = [
    "treatment",
    "clinical trial",
    "randomised",
    "randomized",
    "therapy",
    "drug",
    "intervention",
]
AFRICAN_COUNTRY_NAMES = [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "Cote d'Ivoire",
    "Democratic Republic of the Congo",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Sao Tome and Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Zimbabwe",
]


# Attempts to classify the disease using MeshHeadingList, keywordList, or title/abstract
def parse_pubmed_disease_terms(paper_records, disease_name_to_check):
    disease_name = disease_name_to_check.lower()

    # Check MeshHeadingList first
    MeshHeadingList =
