"""add derived_from and derivation_depth to entity_relations

Revision ID: 386321a1ddd7
Revises: ec1d6421e4e9
Create Date: 2026-08-02 19:00:56.305693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386321a1ddd7'
down_revision: Union[str, Sequence[str], None] = 'ec1d6421e4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_entities_name_domain'), table_name='entities')
    op.add_column('entity_relations', sa.Column('derived_from', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('entity_relations', sa.Column('derivation_depth', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_entity_relations_relationship_id'), table_name='entity_relations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entity_relations_relationship_id'), 'entity_relations', ['relationship_id'], unique=False)
    op.drop_column('entity_relations', 'derivation_depth')
    op.drop_column('entity_relations', 'derived_from')
    op.create_index(op.f('uq_entities_name_domain'), 'entities', [sa.literal_column('lower(TRIM(BOTH FROM name))'), 'domain'], unique=True)
    # ### end Alembic commands ###
