"""add fk indexes

Revision ID: 57bcc7ad89bf
Revises: 002_add_coverage
Create Date: 2026-07-20 08:15:47.140728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bcc7ad89bf'
down_revision: Union[str, Sequence[str], None] = '002_add_coverage'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_entity_relations_from_entity_id', 'entity_relations', ['from_entity_id'], unique=False)
    op.create_index('ix_entity_relations_to_entity_id', 'entity_relations', ['to_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_relations_to_entity_id', table_name='entity-relations')
    op.drop_index('ix_entity_relations_from_entity_id', table_name='entity_relations')
    # ### end Alembic commands ###
