"""Initialize fields

Revision ID: b613893a4af2
Revises: d66d5bb66365
Create Date: 2026-06-09 20:44:24.928233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b613893a4af2'
down_revision: Union[str, Sequence[str], None] = 'd66d5bb66365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('entities', 'creatd_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('creatd_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('entities', 'created_at')
    # ### end Alembic commands ###
