"""create relationship_source table

Revision ID: cd43657a48fb
Revises: d768201a1e1b
Create Date: 2026-06-28 00:57:35.509284

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd43657a48fb"
down_revision: Union[str, Sequence[str], None] = "d768201a1e1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "entities",
        sa.Column("evidence_count", sa.Integer(), nullable=False, server_default="1"),
    )
    op.add_column(
        "entity_relations",
        sa.Column("evidence_count", sa.Integer(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entity_relations", "evidence_count")
    op.drop_column("entities", "evidence_count")
    # ### end Alembic commands ###
